spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:mysql://mydbinstace-1.cb6446g08nav.ap-south-1.rds.amazonaws.com:3306/lms_db
    username: admin
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: 2jX8kPqW3zT2rY8mB5nK4jF6hD1cV0aE2bN9mL7xQ==
  expiration: 3600000